name: namer_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  shared_preferences: ^2.2.1
  
  english_words: ^4.0.0
  provider: ^6.1.2
  flutter_dotenv: ^5.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/Thrift.png
    - assets/background.png
    - assets/Mobile background 2.png
    - assets/Mobile background 3.png
    - .env
